<a href="https://colab.research.google.com/github/FabioCarlesso/ds-study-codes/blob/main/Codes/pos/normalizar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# NORMALIZAÇÃO DE DADOS
# altura 1.70
# peso 85

# objetivos
# 1. normalizar os dados
# 2. salvar modelo de normalização
# 3. discussão sobre estratégias de código

import pandas as pd
import sklearn
from sklearn import preprocessing

dados = pd.read_csv('dados_normalizar.csv', sep=';')
print(dados.head())

   idade  altura  Peso sexo
0     48       1   107    F
1     10       1   240    F
2     79       1    68    F
3     42       1   160    F
4     23       2   157    F


In [ ]:
#1. obter o vetor de valores numéricos
#1.1. segmentar as colunas que são numéricas para normalização quantitiva
print('##################')
dados_num = dados.drop(columns=['sexo'])
dados_categorias = dados['sexo']
print(dados_num)
print(dados_categorias)

##################
     idade  altura  Peso
0       48       1   107
1       10       1   240
2       79       1    68
3       42       1   160
4       23       2   157
..     ...     ...   ...
195     89       2    64
196     15       1    49
197     68       1   140
198     12       1   225
199     73       1    63

[200 rows x 3 columns]
0      F
1      F
2      F
3      F
4      F
      ..
195    M
196    M
197    F
198    M
199    M
Name: sexo, Length: 200, dtype: object


In [ ]:
#1.2 obter o vetor numerico a partir dos dados que são numéricos
print(dados_num.values)
# dados_num.X = dados_num.values
# print(dados_num.X)

[[ 48   1 107]
 [ 10   1 240]
 [ 79   1  68]
 [ 42   1 160]
 [ 23   2 157]
 [ 28   2  99]
 [ 72   1  86]
 [ 61   2  75]
 [ 63   2  68]
 [ 76   1  72]
 [ 45   1 240]
 [ 31   1  34]
 [ 23   1 244]
 [ 41   2 171]
 [ 22   2 219]
 [ 59   1 162]
 [  8   1 198]
 [ 73   2 162]
 [ 56   1 218]
 [ 29   1  35]
 [ 10   1  12]
 [ 51   1  67]
 [ 18   1 224]
 [ 32   2  29]
 [ 61   1 120]
 [ 88   2 127]
 [ 87   2  20]
 [ 81   1 139]
 [  3   2  27]
 [  5   2  26]
 [  1   1 118]
 [ 53   1 208]
 [ 88   2 210]
 [ 51   2 140]
 [ 73   2   6]
 [ 72   2 195]
 [ 72   1  96]
 [ 77   1 216]
 [ 11   2  84]
 [ 44   1 214]
 [ 10   2 203]
 [ 80   2 176]
 [ 40   1 112]
 [ 27   2 135]
 [ 92   2 218]
 [ 78   2  34]
 [  7   2 119]
 [  8   1 213]
 [ 11   2  55]
 [ 45   2  84]
 [100   2  88]
 [ 91   1 187]
 [ 68   1  97]
 [ 52   2 172]
 [ 47   1  25]
 [ 36   2  72]
 [ 15   2   5]
 [ 30   1 221]
 [ 89   2 142]
 [ 26   2 173]
 [ 24   1 130]
 [ 32   2 154]
 [ 65   1  18]
 [ 55   2 213]
 [ 41   1  39]
 [ 59   1 223]
 [ 40   1 

In [ ]:
#2. Normalizar
#2.1. Utilizando o método Min Max manualmente
# z = (x - min(DADOS) / max(DADOS) - min(DADOS))

dados_num.normalizados = (dados_num - dados_num.min())/(dados_num.max()-dados_num.min())
print(dados_num.normalizados)

        idade  altura      Peso
0    0.474747     0.0  0.432653
1    0.090909     0.0  0.975510
2    0.787879     0.0  0.273469
3    0.414141     0.0  0.648980
4    0.222222     1.0  0.636735
..        ...     ...       ...
195  0.888889     1.0  0.257143
196  0.141414     0.0  0.195918
197  0.676768     0.0  0.567347
198  0.111111     0.0  0.914286
199  0.727273     0.0  0.253061

[200 rows x 3 columns]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  """


In [ ]:

#2.2 Utilizando a media manual
# Z = (x-media(atributo)/desvio padrao do atributo)

dados_num.normalizados_media = (dados_num - dados_num.mean())/ (dados_num.std())

print(dados_num.normalizados_media)

        idade    altura      Peso
0   -0.031934 -0.968008 -0.228771
1   -1.358174 -0.968008  1.677653
2    1.049998 -0.968008 -0.787797
3   -0.241341 -0.968008  0.530932
4   -0.904460  1.027884  0.487930
..        ...       ...       ...
195  1.399008  1.027884 -0.845133
196 -1.183669 -0.968008 -1.060144
197  0.666086 -0.968008  0.244252
198 -1.288372 -0.968008  1.462643
199  0.840591 -0.968008 -0.859467

[200 rows x 3 columns]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  """


In [ ]:
# 3. Utilizando o MinMaxScaler()
#3.1 Criar um objeto nomarlizador
normalizador = preprocessing.MinMaxScaler()

#o metodo cria o modelode de normalização com base nos dados
# dados_num.modelo_normalizador = normalizador.fit(dados_num) 

#metodo fit_transform() normaliza os dados retornando um objeto do tipo nparray
dados_num.normalizados_scaler = normalizador.fit_transform(dados_num)
# print(dados_num.normalizados_scaler)
print(normalizador.fit_transform(dados_num))

[[0.47474747 0.         0.43265306]
 [0.09090909 0.         0.9755102 ]
 [0.78787879 0.         0.27346939]
 [0.41414141 0.         0.64897959]
 [0.22222222 1.         0.63673469]
 [0.27272727 1.         0.4       ]
 [0.71717172 0.         0.34693878]
 [0.60606061 1.         0.30204082]
 [0.62626263 1.         0.27346939]
 [0.75757576 0.         0.28979592]
 [0.44444444 0.         0.9755102 ]
 [0.3030303  0.         0.13469388]
 [0.22222222 0.         0.99183673]
 [0.4040404  1.         0.69387755]
 [0.21212121 1.         0.88979592]
 [0.58585859 0.         0.65714286]
 [0.07070707 0.         0.80408163]
 [0.72727273 1.         0.65714286]
 [0.55555556 0.         0.88571429]
 [0.28282828 0.         0.13877551]
 [0.09090909 0.         0.04489796]
 [0.50505051 0.         0.26938776]
 [0.17171717 0.         0.91020408]
 [0.31313131 1.         0.11428571]
 [0.60606061 0.         0.48571429]
 [0.87878788 1.         0.51428571]
 [0.86868687 1.         0.07755102]
 [0.80808081 0.         0.56

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  if __name__ == '__main__':


In [ ]:
# normalizar dados Categoricos
# print('#######')

# incorporar dados normalizados em um dataframe
dados_categorias.normalizados = pd.get_dummies(dados_categorias)

print(type(dados_num.normalizados_scaler))

dados_finais = pd.DataFrame(dados_num.normalizados_scaler, columns=['Idade', 'Altura', 'peso'])
print(dados_finais)

<class 'numpy.ndarray'>
        Idade  Altura      peso
0    0.474747     0.0  0.432653
1    0.090909     0.0  0.975510
2    0.787879     0.0  0.273469
3    0.414141     0.0  0.648980
4    0.222222     1.0  0.636735
..        ...     ...       ...
195  0.888889     1.0  0.257143
196  0.141414     0.0  0.195918
197  0.676768     0.0  0.567347
198  0.111111     0.0  0.914286
199  0.727273     0.0  0.253061

[200 rows x 3 columns]


In [ ]:
dados_finais = dados_finais.join(dados_categorias.normalizados, how='left')
print(dados_finais)

        Idade  Altura      peso  F  M
0    0.474747     0.0  0.432653  1  0
1    0.090909     0.0  0.975510  1  0
2    0.787879     0.0  0.273469  1  0
3    0.414141     0.0  0.648980  1  0
4    0.222222     1.0  0.636735  1  0
..        ...     ...       ... .. ..
195  0.888889     1.0  0.257143  0  1
196  0.141414     0.0  0.195918  0  1
197  0.676768     0.0  0.567347  1  0
198  0.111111     0.0  0.914286  0  1
199  0.727273     0.0  0.253061  0  1

[200 rows x 5 columns]


In [ ]:
dados_finais.to_csv('dados_normalizados_final.csv', index=False, sep=';')